### ISSUE TITLE
KUKA IIWA

### ISSUE THREAD

**Issue by Kastellos** [ogroth/geeco#1]
Hello,

I have a question. Is it possible to change the robot from the gym environment and use a different one? I use a Kuka IIWA in my project. I searched in the mujoco documentation and there is not a model like that. Or is there a way to create my own robot and use it with your pipeline.

Thank you.

**Comment by ogroth** [comment]
Hi Kastellos,
using a different robot is absolutely possible. The Fetch robot used in the simulation is defined [here](https://github.com/ogroth/geeco/blob/main/assets/gym/robots/fetch-gym.xml). The file was adapted from the OpenAI gym package. If you can provide an MJCF description of your robot including the 3D assets (and possibly textures), you should be able to use that as a drop-in replacement. The robot file is included in the environments like shown [here](https://github.com/ogroth/geeco/blob/main/assets/gym/envs/geeco-pad2-cube2.xml#L26). Additionally, meshes, textures and materials pertaining to the robot also need to be registered in the [`defaults` file](https://github.com/ogroth/geeco/blob/main/assets/gym/defaults/geeco-gym.xml#L30). I hope this helps!

**Comment by Kastellos** [comment]
Great thank you for your answer.
